### ISSUE TITLE
Unable to load data - CSV parse error

### ISSUE THREAD

**Issue by FrancescoPeriti** [Garrafao/phitag#14] opened 2023-07-14 19:44 UTC
I am facing an issue while trying to load the 'uses.tsv' file in my project within the application. Although the file is in csv format with tab separator, the application displays an error message stating that there is a csv parse error. Consequently, I am unable to load the file. If it helps I can share my file.

**Comment by FrancescoPeriti** [comment] 2023-07-17 05:56
I noticed that some files are correctly loaded, while others are not, even though they are all valid TSV files

**Comment by confusedSerge** [comment] 2023-07-17 07:07
Would it be possible for you to post a small file/selection to recreate the problem?

**Comment by FrancescoPeriti** [comment] 2023-07-17 07:10
dataID	context	indices_target_token	indices_target_sentence	lemma
16_(1 Peter 4:7)	BLACK SATURDAY 🕊️ The end of all things is near. Therefore be alert and of sober mind so that you may pray.	18:47	0:107	The end of all things is near
17_(1 Peter 4:7)	The end of all things is near. You must be self-controlled and alert	0:29	0:68	The end of all things is near
18_(1 Peter 4:7)	The end of all things is near. The nations must now prepare for eternity.	0:29	0:73	The end of all things is near
19_(1 Peter 4:7)	Love like the world will end tomorrow. The end of all things is near.	39:68	0:69	The end of all things is near
12_(Job 1:1)	I'm starting to read "Can you pull in Leviathan with a Fishhook?" I'm sooo excited 🥰 🥰 🥰	22:63	0:88	Can you pull in Leviathan with a Fishhook
13_(Job 1:1)	I've read a story veryyyy similar to this! It's called Can you pull in Leviathan with a Fishhook? Highly NSFW so I reccomend you read the tags, anyways enjoy.	55:96	0:158	Can you pull in Leviathan with a Fishhook
14_(Job 1:1)	Today my sons & I stomped through the swamplands in south western florida.  Soon we will be stomping through Texas with our brand new alligator boots from this bad boy that measured 12 ft 5! Job 41:1. "Can you pull in Leviathan with a Fishhook or press down his tongue with a cord"	202:243	0:281	Can you pull in Leviathan with a Fishhook
15_(Job 1:1)	Evil isn’t a philosophical problem to be solved but a murderous sea monster to be slayed. "Can you pull in Leviathan with a Fishhook or tie down its tongue with a rope?"	91:132	0:169	Can you pull in Leviathan with a Fishhook
0_(Luke 24:15)	While they were talking and discussing together, Jesus himself drew near and went with them. But their eyes were kept from recognizing him. Being a disciple of Jesus can be confusing at times, especially when we're still in the infancy of our faith.	0:91	0:249	While they were talking and discussing together, Jesus himself drew near and went with them
1_(Luke 24:15)	Jesus is willing to walk down whatever road you are on. Allow your eyes and heart to be opened to Him! He is near. While they were talking and discussing together, Jesus himself drew near and went with them	115:206	0:206	While they were talking and discussing together, Jesus himself drew near and went with them
2_(Luke 24:15)	God is present even when His presence isn't directly noticed: "While they were talking and discussing together, Jesus himself drew near and went with them" (Luke 24:15).	63:154	0:169	While they were talking and discussing together, Jesus himself drew near and went with them
3_(Luke 24:15)	Adventures in Bible Study. While they were talking and discussing together, Jesus himself drew near... . - [SWOOP] - <Multiple Shrieks>: BAT!!!  - SWOOP SWOOP SWOOP SWOOPITY SWOOP SWOOP #BatsAndThePelfrey #BatsInTheBelfrey #JesusIsThatYou	27:99	0:238	While they were talking and discussing together, Jesus himself drew near and went with them
20_(Matthew 5:9)	There are no real winners in war. Blessed are the peacemakers.	34:61	0:62	Blessed are the peacemakers
21_(Matthew 5:9)	STOP THE WAR!! Blessed are the peacemakers, for they will be called children of God	15:42	0:83	Blessed are the peacemakers
22_(Matthew 5:9)	As the Bible says, "Blessed are the peacemakers." I will be your Peacemaker - and I am the only one who will prevent World War Three." - President Trump speaking at @FaithandFreedom	20:47	0:181	Blessed are the peacemakers
23_(Matthew 5:9)	TRUMP: "Before I even arrive at the Oval Office, I will have the horrible war between Russia and Ukraine settled in 24 hours. As the Bible says, "Blessed are the peacemakers." And I will be your peacemaker."	146:173	0:207	Blessed are the peacemakers
24_(Matthew 5:9)	TRUMP: I will work with Ukraine and Russia to end the war in 24 hours. As the Bible says, Blessed are the Peacemakers	90:117	0:117	Blessed are the peacemakers
25_(Matthew 5:9)	Jesus in the Bible said that peacemakers would be known as the children of God. Not the fear mongers. Not the authoritarians. Not the gatekeepers. Not those who see their religion as a war against the world. He said, "Blessed are the peacemakers, for they will be called children of God."	218:245	0:288	Blessed are the peacemakers
26_(Matthew 5:9)	Blessed are the peacemakers for them shall be called children of God. Nowhere in the Bible am I required to be pro war. I advocate against war. Diplomacy is preferable to war.	0:27	0:175	Blessed are the peacemakers
6_(Proverbs 1:8)	May Christian parents raise their families  wisely by immersing themselves first in the word of God: Listen, my son, to your father’s instruction and do not forsake your mother’s teaching. They are a garland to grace your head and a chain to adorn your neck. 	101:187	0:259	Listen, my son, to your father’s instruction and do not forsake your mother’s teaching
7_(Proverbs 1:8)	"Listen, my son, to your father’s instruction and do not forsake your mother’s teaching." Your parents have pure motives, they only want the best for you in a healthy family.	1:87	0:174	Listen, my son, to your father’s instruction and do not forsake your mother's teaching
8_(Proverbs 1:8)	Join with us this morning in prayer for our education system and youth. Let's pray Proverbs 1:8, i.e. Listen, my son, to your father’s instruction and do not forsake your mother’s teaching.	102:188	0:189	Listen, my son, to your father’s instruction and do not forsake your mother's teaching
4_(Revelation 12:3)	William Blake - The Great Red Dragon and the Woman Clothed in Sun. This painting illustrates passages that describe "an enormous red dragon with seven heads and ten horns and seven crowns on his heads\" who descends upon \"a woman clothed with the sun, with the moon under her feet."	117:200	0:281	an enormous red dragon with seven heads and ten horns and seven crowns on his heads
5_(Revelation 12:3)	Communist China is the Red Dragon in Revelation. The 7 heads represent Freemasonry, which secretly undermined Nationalist China in the civil war. Then another sign appeared in heaven: an enormous red dragon with seven heads and ten horns and seven crowns on his heads."	184:267	0:269	an enormous red dragon with seven heads and ten horns and seven crowns on his heads
9_(Song of songs 8:6)	As Louisa recites her vows, Chuuya feels someone burning a hole in the side of his head. "Place me like a seal over your heart, like a seal on your arm, for love is as strong as death, its jealousy as enduring as the grave". He swallows and turns his head ever so slightly.	90:126	0:273	Place me like a seal over your heart
10_(Song of songs 8:6)	Did you know that Jesus is wearing a necklace with your name on it? That’s how much you are on his heart right now! How do I know? Because we are his beloved! "Place me like a seal over your heart"	160:196	0:197	Place me like a seal over your heart
11_(Song of songs 8:6)	Commitment to your spouse as described by the bride in Song of Solomon 8:6... sounds like a woman I love......  "Place me like a seal over your heart, like a seal on your arm; for love is as strong as death, its jealousy unyielding as the grave."	113:149	0:246	Place me like a seal over your heart
27_(Zechariah 10:1)	We need rain... We pray for rain... God hears us and answers... Ask the Lord for rain in the springtime	64:103	0:103	Ask the Lord for rain in the springtime
28_(Zechariah 10:1)	Uff... So sad, rain to lift my spirits! "Ask the LORD for rain in the springtime". Thanks	41:80	0:89	Ask the Lord for rain in the springtime
29_(Zechariah 10:1)	Ask the Lord for rain in the springtime; it is the LORD who sends the thunderstorms. He gives showers of rain to all people, and plants of the field to everyone. Happy rainy season dear farmers, today presents a great opportunity to feed this universe again.	0:39	0:258	Ask the Lord for rain in the springtime

**Comment by confusedSerge** [comment] 2023-07-17 12:38
Thanks for finding this bug. The problem is fixed, the error message is extended and will be integrated soon into the online version. Make sure, that your files are UTF-8 encoded. The provided file is encoded in UTF-8 with BOM, which causes some issues with our parser solution.

**Closed** 2023-07-18 15:57 UTC

**Comment by FrancescoPeriti** [comment] 2023-07-19 06:59
@confusedSerge 
Hi, problems solved, thanks. 

However, I face the same issue 'CSV parse error' when I try to load the judgments file for the tutorial phase. This is my utf-8 file: I've already removed bom.
[judgments.csv](https://github.com/Garrafao/phitag/files/12091987/judgments.csv)

**Comment by confusedSerge** [comment] 2023-07-22 08:23
Hey, when I look at the file, there seems to be some incorrect tabbing between comment and annotator, making the file only containing three columns ("instanceID", "label", "comment annotator"). I am not able to check if fixing this will result in a correct upload. Let me know, if this helps, if not, I will reopen this issue.

**Comment by FrancescoPeriti** [comment] 2023-07-24 08:07
Sorry, I didn't notice. Fixing the file solved the problem. Thanks
